### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by jacopodona** [rthapa84/sleepfm-codebase#1]
Hi! Really interesting work! Since the dataset is private and CinC is much smaller, could you share the model weights achieved on your dataset? Thank you.

**Comment by rthapa84** [comment]
Hey, thank you for reaching out and glad you found our work interesting. I plan to release one model checkpoint towards the end of this week. Please stay tuned!

**Comment by rthapa84** [comment]
Hey, I just added a model checkpoint inside sleepfm/checkpoint. I hope this helps. Note that this is a really small model. We are currently working on a larger version with some architectural improvements and trained on more data. We will be releasing the codebase and model for that soon as well. Stay tuned!👀

**Comment by jacopodona** [comment]
Thanks!
